### ISSUE TITLE
cache cleanup raise Error in Python 3

### ISSUE THREAD

**Issue by alexyzhou** [stucchio/Python-LRU-cache#14]
When cache expires in Python3, will have the following error:
ERROR:root:Exception calling application: OrderedDict mutated during iteration
Traceback
File "/opt/conda/lib/python3.6/site-packages/lru/__init__.py", line 32, in withlock
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/lru/__init__.py", line 160, in __setitem__
    self.cleanup()
  File "/opt/conda/lib/python3.6/site-packages/lru/__init__.py", line 32, in withlock
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/lru/__init__.py", line 184, in cleanup
    for k in self.__expire_times:
RuntimeError: OrderedDict mutated during iteration

I found similar issues in https://github.com/coddingtonbear/python-myfitnesspal/issues/26, suggest change the code to: for k in list(self.__expire_times.keys())

**Comment by truebit** [comment]
## Usage in Python3

Note that this module should probably not be used in python3 projects, since the [standard library already has one](https://docs.python.org/3/library/functools.html). The only feature this one has which that one lacks is timed eviction.

**Comment by alexyzhou** [comment]
Although python3 has the standard one, it doesn't have expiry functionality which I needed in my project.

**Comment by truebit** [comment]
https://github.com/stucchio/Python-LRU-cache/pull/13
